### ISSUE TITLE
[Feature Request] Rename & Move

### ISSUE THREAD

**Issue by locuturus** [w2sv/FileNavigator#24]
### Overview

DocumentsUI has a name and save feature, can that be added to FileNavigator? Right now I can select a folder but I can't change the filename.

**Comment by w2sv** [comment]
Should definitely be possible, I'll see what I can do.

**Comment by w2sv** [comment]
Implemented in [0.2.2](https://github.com/w2sv/FileNavigator/releases/tag/0.2.2) :)
