### ISSUE TITLE
[Feature Request] autostart

### ISSUE THREAD

**Issue by theotheroracle** [w2sv/FileNavigator#35]
I would love an option to autostart this service on boot !!

**Comment by w2sv** [comment]
You can now enabled that on the bottom of the navigator settings screen in [0.2.0](https://github.com/w2sv/FileNavigator/releases/tag/0.2.0). Lmk if it doesn't work as expected.

**Comment by yephny** [comment]
@w2sv There is a problem with the switch on my device. Although it's off, File Navigator  still auto starts.
