### ISSUE TITLE
[Feature Request] Cloud Storage

### ISSUE THREAD

**Issue by cbpandya** [w2sv/FileNavigator#57]
### Overview

Please Add Selection Of Cloud Storage Like Onedrive Gdrive terabox In Automation

**Comment by w2sv** [comment]
Would be a neat addition indeed, I'll start working on it asap.

**Comment by w2sv** [comment]
I implemented moving to cloud storage providers in [0.2.2](https://github.com/w2sv/FileNavigator/releases/tag/0.2.2). Auto moving to those destinations remains impossible though, this would require a hell of a lot of specific authentication stuff for every single provider to obtain the permissions to do that.
Let me know how the non-auto moving works for you.
