### ISSUE TITLE
[Bug] Settings resets to default after some time

### ISSUE THREAD

**Issue by AndyMagnom** [w2sv/FileNavigator#65]
I enabled auto move for images and videos and turned off "Disable on low battery" and Turned on "Start on system boot"

After an hour or 2 passed the settings resets, the auto move returns to notify and "Disable on low battery" turns on and "Start on system boot" turns off

I have the latest release from F-Droid (IzzyOnDroid) 

**How to reproduce** 
1. Go to Navigation settings
2. Change the default settings
3. Close the app for sometime
4. Reopen it and go to the settings

Version
0.2.0

Android Version
14

Device Model
Realme C53

**Comment by w2sv** [comment]
Yeah that was a data store migration based issue, where a flag representing whether the migration should be performed would sometimes get lost, leading to it being performed inadequately, thereby resetting the configuration. Sorry about that, I imagine that's annoying.
I (hopefully) resolved that in the [new version](https://github.com/w2sv/FileNavigator/releases/tag/0.2.1). Should it persist, however, please reopen the issue!!!
