### ISSUE TITLE
All rhe settings gets changed to notify after a reboot. 

### ISSUE THREAD

**Issue by Spy-boy** [w2sv/FileNavigator#68]
### Overview

![Screenshot_20240904-185440](https://github.com/user-attachments/assets/f4aaa9f6-a3b2-4de5-a6e9-a102bcb05dcf)

### How to reproduce

Create a path/File directory in app settings.
Apply the settings.
Reboot the device.
Open app and the settings will be changed to 'Notify'.

### Version

0.2.0

### Android Version

14

### Device Model

Nothing 2a

**Comment by w2sv** [comment]
That should be caused by the same issue that also led to #65.
I'll cite my answer from there:

> Yeah that was a data store migration based issue, where a flag representing whether the migration should be performed would sometimes get lost, leading to it being performed inadequately, thereby resetting the configuration. Sorry about that, I imagine that's annoying.
I (hopefully) resolved that in the [new version](https://github.com/w2sv/FileNavigator/releases/tag/0.2.1). Should it persist, however, please reopen the issue!!!

Thank you for reporting! Cheers :)
