### ISSUE TITLE
[Bug] Settings lost over time 

### ISSUE THREAD

**Issue by darrenkperth** [w2sv/FileNavigator#73]
### Overview

Settings for auto saving reverts to notification defaults over time 

### How to reproduce

Occuarance is random and difficult to reproduce. 

### Version

0.20

### Android Version

Android 14

### Device Model

Samsung Fold 6

**Comment by w2sv** [comment]
I already fixed that in version 0.2.1, but Google rejected the Playstore update for a rather implausible reason. You could get the new version from one of the other sources I published it on. It will possibly be at some point available on the Playstore too, though.
